class TableNames:
	HOSPITAL_TABLE_NAME = "Hospital"
	PATIENT_TABLE_NAME = "Patient"
	EXAMINATION_TABLE_NAME = "Examination"
	CLINICAL_RECORD_TABLE_NAME = "ClinicalRecord"
	PHENOTYPIC_RECORD_TABLE_NAME = "PhenotypicRecord"
	DISEASE_RECORD_TABLE_NAME = "DiseaseRecord"
	DISEASE_TABLE_NAME = "Disease"

