# Table names
HOSPITAL_TABLE_NAME = "Hospital"
PATIENT_TABLE_NAME = "Patient"
EXAMINATION_TABLE_NAME = "Examination"
EXAMINATION_RECORD_TABLE_NAME = "ExaminationRecord"
DISEASE_TABLE_NAME = "Disease"
DISEASE_RECORD_TABLE_NAME = "DiseaseRecord"


# Counters for identifiers
HOSPITAL_COUNTER = 1
PATIENT_COUNTER = 1
EXAMINATION_COUNTER = 1
EXAMINATION_RECORD_COUNTER = 1
DISEASE_COUNTER = 1
DISEASE_RECORD_COUNTER = 1

